name: MiddleCraft-CORE
api-version: 1.20
author: Percy_Game
version: 0.0
main: fr.percygame.middlecraft.Main
commands:
  pay:
    description: allow a player to give to an other a certain amount of his personnal balance
  orens_give:
    permission: admin.use
    description: give the admins the ability to give money to a player
  orens_withdraw:
    permission: admin.use
    description: give the admins the ability to remove any money from a player
  t:
    description: for all the commands about town managment
